### ISSUE TITLE
Nokia 8110 4G **cursor**

### ISSUE THREAD

**Issue by WebReflection** [amanboss9/naviboard#4]
I've tested this library but Nokia 8110 4G shows the cursor and instead of firing `"keydown"` events it fires `"mousemove"`, plus there's apparently no way to get rid of that cursor, even if native KaiOS UI doesn't show it.

TL;DR has anyone tried this on Nokia 8110 4G and, if that's the case, how did you trap the spatial navigation into keydown events instead of mousemove ?

**Comment by amanboss9** [comment]
I believe you have to check your manifest.webapp file which might be having cursor : true property. If this is the case it will fires up `mousemove` instead of `keydown`.

**Comment by WebReflection** [comment]
@amanboss9 so this library won't work on regular websites?

**Comment by amanboss9** [comment]
It will definitely work. What i am talking about is the case when you are working with feature phone. The D-pad will give you `mousemove` event instead of `keydown`, so in that case manifest comes in scene. Otherwise if you are working with regular website, keyboard arrow keys will definitely give `keydown` and the library would work. @webReflection you can look the examples i attached in README.md.

**Comment by WebReflection** [comment]
> the case when you are working with feature phone

I am, I have a Nokia 8110 4G and its cursor takes over my `keydown` listeners, and never trigger an event different from `mousemove`, so ... are you testing this library against real Nokia 8110 4G device?

_TL;DR_ I don't care about simulators ... I'm talking about real devices

**Comment by WebReflection** [comment]
to simplify, give me a live web page to demonstrate this library works on Nokia 8110 4G too, and I'll double check that with my Nokia 8110 4G device.

In that case, if it works, I'll close this bug.

Thanks!

**Comment by amanboss9** [comment]
@WebReflection I don't have Nokia 8110 4G to test the library but if  your application has **manifest.webapp** then just check for the property **cursor**. If you find it `true` then make it `false` or remove it. As far as my experience with KAIOS devices and application is concern, i have noticed that if we put the mentioned property `cursor : true` in the application the arrow buttons in the D-pad starts giving `mousemove` events instead of  `keydown`. Jio phones in India are running on KAIOS and have both kind of applications in it. _For Ex._ Facebook has given cursor feature but other native applications are managing focus by `keydown` only.  I have tried cursor property with other KAIOS phone and it was giving me `mousemove` event instead of `keydown` . 

Let me know if it still don't work!

**Comment by WebReflection** [comment]
@amanboss9 thanks for taking time to answer but no, it doesn't work for me. Manifest or not, true or false as boolean or string, it seems to make no difference.

At some point I thought it was this library, so I've tested with mine but the result is the same.

You can try a live demo here: https://tweety.now.sh

With Nokia 8110 4G I have to press 2 so that the display/cursor switches to _touch_ events mode and at that point I can intercept those and work around it.

However, in my ideal world. I want to `cusror: none;` via CSS and disable fully on the phone so that the arrow doesn't exist and I can actually surf like I can already with my keyboard.

**Comment by WebReflection** [comment]
since there's nothing this lib can do, I'm closing this.
